
from os import getenv

logs_path = getenv('LOGS_PATH')

mongo_ip = getenv('MONGO_IP')
mongo_port = int(getenv('MONGO_PORT'))


token = getenv('TELEGRAM_TOKEN')

ADMIN_MAIN_MENU = 0

MESSAGE_CONFIRM = 1
MAILING = 2

CREATE_EVENT, CREATE_EVENT_CONFIRM, EVENT_NAME, EVENT_DT, EVENT_DESC, EVENT_CATEGORY = 3, 4, 5, 6, 7, 8
SUPPORT_SELECT_QUEST, SUPPORT_ANSWER_QUEST, SUPPORT_ANSWER_QUEST_CONFIRM = 9, 10, 11

AUTH_CODE = 12
USER_MENU = 13
MATERIALS = 14
DAY_PROGRAM = 15
EVENTS_CAT = 16
EVENTS_DAY = 17
EVENTS_EVENT = 18
EVENT_CONFIRM = 19